# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_app_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1405, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1060, 30, 281, 871))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RobustCovButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.RobustCovButton.setFont(font)
        self.RobustCovButton.setObjectName("RobustCovButton")
        self.verticalLayout.addWidget(self.RobustCovButton)
        self.OneClassSVMButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.OneClassSVMButton.setFont(font)
        self.OneClassSVMButton.setObjectName("OneClassSVMButton")
        self.verticalLayout.addWidget(self.OneClassSVMButton)
        self.IsolationForestButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.IsolationForestButton.setFont(font)
        self.IsolationForestButton.setObjectName("IsolationForestButton")
        self.verticalLayout.addWidget(self.IsolationForestButton)
        self.LocalOutlierButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LocalOutlierButton.setFont(font)
        self.LocalOutlierButton.setObjectName("LocalOutlierButton")
        self.verticalLayout.addWidget(self.LocalOutlierButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.SaveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout.addWidget(self.SaveButton)
        self.DataFrame = QtWidgets.QFrame(self.centralwidget)
        self.DataFrame.setGeometry(QtCore.QRect(30, 30, 1011, 871))
        self.DataFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DataFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DataFrame.setObjectName("DataFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1405, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RobustCovButton.setText(_translate("MainWindow", "Robust Covariance"))
        self.OneClassSVMButton.setText(_translate("MainWindow", "One-Class SVM"))
        self.IsolationForestButton.setText(_translate("MainWindow", "Isolation Forest"))
        self.LocalOutlierButton.setText(_translate("MainWindow", "Local Outlier Factor"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
